# Generated by Django 3.2.3 on 2021-07-06 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_blog_post_slugified'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_post',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
