# Generated by Django 3.2.3 on 2021-07-07 23:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0005_blog_post_author'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blog_Post',
            new_name='Post',
        ),
    ]
